const actionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
    POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS',
    POST_ORDER_FAILED: 'POST_ORDER_FAILED',
    PURCHASE_STARTED: 'PURCHASE_STARTED',

    SET_ORDERS: 'SET_ORDERS',
    FETCH_ORDERS_FAILED: 'FETCH_ORDERS_FAILED',
    REMOVE_ERROR: 'REMOVE_ERROR',

    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILED: 'AUTH_FAILED',
    AUTH_SAVE_USER: 'AUTH_SAVE_USER',
    AUTH_REMOVE_USER: 'AUTH_REMOVE_USER'
};

export default actionTypes;