const actionTypes = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
    POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS',
    POST_ORDER_FAILED: 'POST_ORDER_FAILED',
    SET_ORDERS: 'SET_ORDERS',
    FETCH_ORDERS_FAILED: 'FETCH_ORDERS_FAILED',
    REMOVE_ERROR: 'REMOVE_ERROR',
    PURCHASE_STARTED: 'PURCHASE_STARTED'
};

export default actionTypes;